// File generated from our OpenAPI spec by Stainless.

package dev.relayapi.models.tools.validate

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.relayapi.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ValidateCheckPostLengthResponseTest {

    @Test
    fun create() {
        val validateCheckPostLengthResponse =
            ValidateCheckPostLengthResponse.builder()
                .platforms(
                    ValidateCheckPostLengthResponse.Platforms.builder()
                        .bluesky(
                            ValidateCheckPostLengthResponse.Platforms.Bluesky.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .discord(
                            ValidateCheckPostLengthResponse.Platforms.Discord.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .facebook(
                            ValidateCheckPostLengthResponse.Platforms.Facebook.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .googlebusiness(
                            ValidateCheckPostLengthResponse.Platforms.Googlebusiness.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .instagram(
                            ValidateCheckPostLengthResponse.Platforms.Instagram.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .linkedin(
                            ValidateCheckPostLengthResponse.Platforms.Linkedin.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .mastodon(
                            ValidateCheckPostLengthResponse.Platforms.Mastodon.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .pinterest(
                            ValidateCheckPostLengthResponse.Platforms.Pinterest.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .reddit(
                            ValidateCheckPostLengthResponse.Platforms.Reddit.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .sms(
                            ValidateCheckPostLengthResponse.Platforms.Sms.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .snapchat(
                            ValidateCheckPostLengthResponse.Platforms.Snapchat.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .telegram(
                            ValidateCheckPostLengthResponse.Platforms.Telegram.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .threads(
                            ValidateCheckPostLengthResponse.Platforms.Threads.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .tiktok(
                            ValidateCheckPostLengthResponse.Platforms.Tiktok.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .twitter(
                            ValidateCheckPostLengthResponse.Platforms.Twitter.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .whatsapp(
                            ValidateCheckPostLengthResponse.Platforms.Whatsapp.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .youtube(
                            ValidateCheckPostLengthResponse.Platforms.Youtube.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(validateCheckPostLengthResponse.platforms())
            .isEqualTo(
                ValidateCheckPostLengthResponse.Platforms.builder()
                    .bluesky(
                        ValidateCheckPostLengthResponse.Platforms.Bluesky.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .discord(
                        ValidateCheckPostLengthResponse.Platforms.Discord.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .facebook(
                        ValidateCheckPostLengthResponse.Platforms.Facebook.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .googlebusiness(
                        ValidateCheckPostLengthResponse.Platforms.Googlebusiness.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .instagram(
                        ValidateCheckPostLengthResponse.Platforms.Instagram.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .linkedin(
                        ValidateCheckPostLengthResponse.Platforms.Linkedin.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .mastodon(
                        ValidateCheckPostLengthResponse.Platforms.Mastodon.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .pinterest(
                        ValidateCheckPostLengthResponse.Platforms.Pinterest.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .reddit(
                        ValidateCheckPostLengthResponse.Platforms.Reddit.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .sms(
                        ValidateCheckPostLengthResponse.Platforms.Sms.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .snapchat(
                        ValidateCheckPostLengthResponse.Platforms.Snapchat.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .telegram(
                        ValidateCheckPostLengthResponse.Platforms.Telegram.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .threads(
                        ValidateCheckPostLengthResponse.Platforms.Threads.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .tiktok(
                        ValidateCheckPostLengthResponse.Platforms.Tiktok.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .twitter(
                        ValidateCheckPostLengthResponse.Platforms.Twitter.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .whatsapp(
                        ValidateCheckPostLengthResponse.Platforms.Whatsapp.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .youtube(
                        ValidateCheckPostLengthResponse.Platforms.Youtube.builder()
                            .count(0.0)
                            .limit(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val validateCheckPostLengthResponse =
            ValidateCheckPostLengthResponse.builder()
                .platforms(
                    ValidateCheckPostLengthResponse.Platforms.builder()
                        .bluesky(
                            ValidateCheckPostLengthResponse.Platforms.Bluesky.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .discord(
                            ValidateCheckPostLengthResponse.Platforms.Discord.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .facebook(
                            ValidateCheckPostLengthResponse.Platforms.Facebook.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .googlebusiness(
                            ValidateCheckPostLengthResponse.Platforms.Googlebusiness.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .instagram(
                            ValidateCheckPostLengthResponse.Platforms.Instagram.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .linkedin(
                            ValidateCheckPostLengthResponse.Platforms.Linkedin.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .mastodon(
                            ValidateCheckPostLengthResponse.Platforms.Mastodon.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .pinterest(
                            ValidateCheckPostLengthResponse.Platforms.Pinterest.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .reddit(
                            ValidateCheckPostLengthResponse.Platforms.Reddit.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .sms(
                            ValidateCheckPostLengthResponse.Platforms.Sms.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .snapchat(
                            ValidateCheckPostLengthResponse.Platforms.Snapchat.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .telegram(
                            ValidateCheckPostLengthResponse.Platforms.Telegram.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .threads(
                            ValidateCheckPostLengthResponse.Platforms.Threads.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .tiktok(
                            ValidateCheckPostLengthResponse.Platforms.Tiktok.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .twitter(
                            ValidateCheckPostLengthResponse.Platforms.Twitter.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .whatsapp(
                            ValidateCheckPostLengthResponse.Platforms.Whatsapp.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .youtube(
                            ValidateCheckPostLengthResponse.Platforms.Youtube.builder()
                                .count(0.0)
                                .limit(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedValidateCheckPostLengthResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(validateCheckPostLengthResponse),
                jacksonTypeRef<ValidateCheckPostLengthResponse>(),
            )

        assertThat(roundtrippedValidateCheckPostLengthResponse)
            .isEqualTo(validateCheckPostLengthResponse)
    }
}
