// File generated from our OpenAPI spec by Stainless.

package dev.relayapi.models.tools.validate

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import dev.relayapi.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ValidateValidateMediaResponseTest {

    @Test
    fun create() {
        val validateValidateMediaResponse =
            ValidateValidateMediaResponse.builder()
                .accessible(true)
                .platformLimits(
                    ValidateValidateMediaResponse.PlatformLimits.builder()
                        .bluesky(
                            ValidateValidateMediaResponse.PlatformLimits.Bluesky.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .discord(
                            ValidateValidateMediaResponse.PlatformLimits.Discord.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .facebook(
                            ValidateValidateMediaResponse.PlatformLimits.Facebook.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .googlebusiness(
                            ValidateValidateMediaResponse.PlatformLimits.Googlebusiness.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .instagram(
                            ValidateValidateMediaResponse.PlatformLimits.Instagram.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .linkedin(
                            ValidateValidateMediaResponse.PlatformLimits.Linkedin.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .mastodon(
                            ValidateValidateMediaResponse.PlatformLimits.Mastodon.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .pinterest(
                            ValidateValidateMediaResponse.PlatformLimits.Pinterest.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .reddit(
                            ValidateValidateMediaResponse.PlatformLimits.Reddit.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .sms(
                            ValidateValidateMediaResponse.PlatformLimits.Sms.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .snapchat(
                            ValidateValidateMediaResponse.PlatformLimits.Snapchat.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .telegram(
                            ValidateValidateMediaResponse.PlatformLimits.Telegram.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .threads(
                            ValidateValidateMediaResponse.PlatformLimits.Threads.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .tiktok(
                            ValidateValidateMediaResponse.PlatformLimits.Tiktok.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .twitter(
                            ValidateValidateMediaResponse.PlatformLimits.Twitter.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .whatsapp(
                            ValidateValidateMediaResponse.PlatformLimits.Whatsapp.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .youtube(
                            ValidateValidateMediaResponse.PlatformLimits.Youtube.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .build()
                )
                .contentType("content_type")
                .size(0.0)
                .build()

        assertThat(validateValidateMediaResponse.accessible()).isEqualTo(true)
        assertThat(validateValidateMediaResponse.platformLimits())
            .isEqualTo(
                ValidateValidateMediaResponse.PlatformLimits.builder()
                    .bluesky(
                        ValidateValidateMediaResponse.PlatformLimits.Bluesky.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .discord(
                        ValidateValidateMediaResponse.PlatformLimits.Discord.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .facebook(
                        ValidateValidateMediaResponse.PlatformLimits.Facebook.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .googlebusiness(
                        ValidateValidateMediaResponse.PlatformLimits.Googlebusiness.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .instagram(
                        ValidateValidateMediaResponse.PlatformLimits.Instagram.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .linkedin(
                        ValidateValidateMediaResponse.PlatformLimits.Linkedin.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .mastodon(
                        ValidateValidateMediaResponse.PlatformLimits.Mastodon.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .pinterest(
                        ValidateValidateMediaResponse.PlatformLimits.Pinterest.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .reddit(
                        ValidateValidateMediaResponse.PlatformLimits.Reddit.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .sms(
                        ValidateValidateMediaResponse.PlatformLimits.Sms.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .snapchat(
                        ValidateValidateMediaResponse.PlatformLimits.Snapchat.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .telegram(
                        ValidateValidateMediaResponse.PlatformLimits.Telegram.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .threads(
                        ValidateValidateMediaResponse.PlatformLimits.Threads.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .tiktok(
                        ValidateValidateMediaResponse.PlatformLimits.Tiktok.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .twitter(
                        ValidateValidateMediaResponse.PlatformLimits.Twitter.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .whatsapp(
                        ValidateValidateMediaResponse.PlatformLimits.Whatsapp.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .youtube(
                        ValidateValidateMediaResponse.PlatformLimits.Youtube.builder()
                            .maxSize(0.0)
                            .withinLimit(true)
                            .build()
                    )
                    .build()
            )
        assertThat(validateValidateMediaResponse.contentType()).contains("content_type")
        assertThat(validateValidateMediaResponse.size()).contains(0.0)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val validateValidateMediaResponse =
            ValidateValidateMediaResponse.builder()
                .accessible(true)
                .platformLimits(
                    ValidateValidateMediaResponse.PlatformLimits.builder()
                        .bluesky(
                            ValidateValidateMediaResponse.PlatformLimits.Bluesky.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .discord(
                            ValidateValidateMediaResponse.PlatformLimits.Discord.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .facebook(
                            ValidateValidateMediaResponse.PlatformLimits.Facebook.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .googlebusiness(
                            ValidateValidateMediaResponse.PlatformLimits.Googlebusiness.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .instagram(
                            ValidateValidateMediaResponse.PlatformLimits.Instagram.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .linkedin(
                            ValidateValidateMediaResponse.PlatformLimits.Linkedin.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .mastodon(
                            ValidateValidateMediaResponse.PlatformLimits.Mastodon.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .pinterest(
                            ValidateValidateMediaResponse.PlatformLimits.Pinterest.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .reddit(
                            ValidateValidateMediaResponse.PlatformLimits.Reddit.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .sms(
                            ValidateValidateMediaResponse.PlatformLimits.Sms.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .snapchat(
                            ValidateValidateMediaResponse.PlatformLimits.Snapchat.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .telegram(
                            ValidateValidateMediaResponse.PlatformLimits.Telegram.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .threads(
                            ValidateValidateMediaResponse.PlatformLimits.Threads.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .tiktok(
                            ValidateValidateMediaResponse.PlatformLimits.Tiktok.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .twitter(
                            ValidateValidateMediaResponse.PlatformLimits.Twitter.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .whatsapp(
                            ValidateValidateMediaResponse.PlatformLimits.Whatsapp.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .youtube(
                            ValidateValidateMediaResponse.PlatformLimits.Youtube.builder()
                                .maxSize(0.0)
                                .withinLimit(true)
                                .build()
                        )
                        .build()
                )
                .contentType("content_type")
                .size(0.0)
                .build()

        val roundtrippedValidateValidateMediaResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(validateValidateMediaResponse),
                jacksonTypeRef<ValidateValidateMediaResponse>(),
            )

        assertThat(roundtrippedValidateValidateMediaResponse)
            .isEqualTo(validateValidateMediaResponse)
    }
}
